# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  PORT = 8080
  ARCH = "64"
  config.vm.box = "hashicorp/precise#{ARCH}"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: PORT
  config.vm.network "private_network", ip: "192.168.33.10"
		 
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y apache2
   SHELL
end
